#!/bin/bash
set -x

source ~/awskeys

D=`date +"%Y%m%d%H%M"`
file=${D}.csv
filepath=/tmp/${file}

cp /tmp/data.csv ${filepath}
rm /tmp/data.csv

bucket="www.plantbio.org"
resource="/${bucket}/data/${file}"
contentType="text/csv"
dateValue=`date -R`
stringToSign="PUT\n\n${contentType}\n${dateValue}\n${resource}"
signature=`echo -en ${stringToSign} | openssl sha1 -hmac ${s3Secret} -binary | base64`

curl -k \
     --silent \
     -X PUT -T "${filepath}" \
     -H "Host: ${bucket}.s3.amazonaws.com" \
     -H "Date: ${dateValue}" \
     -H "Content-Type: ${contentType}" \
     -H "Authorization: AWS ${s3Key}:${signature}" \
     https://${bucket}.s3.amazonaws.com/data/${file}

rm -f ${filepath}
